Traceback (most recent call last):
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/sam/miniforge3/envs/dev/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
columns = ['name', 'sleep_total']

rows = f.name.re_match('.*mouse.*', flags = re.IGNORECASE)

DT[rows, columns]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_73068/3095691404.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mcolumns[0m [0;34m=[0m [0;34m[[0m[0;34m'name'[0m[0;34m,[0m [0;34m'sleep_total'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mrows[0m [0;34m=[0m [0mf[0m[0;34m.[0m[0mname[0m[0;34m.[0m[0mre_match[0m[0;34m([0m[0;34m'.*mouse.*'[0m[0;34m,[0m [0mflags[0m [0;34m=[0m [0mre[0m[0;34m.[0m[0mIGNORECASE[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mDT[0m[0;34m[[0m[0mrows[0m[0;34m,[0m [0mcolumns[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: FExpr.re_match() got an unexpected keyword argument flags
TypeError: FExpr.re_match() got an unexpected keyword argument flags

